ALTER TABLE social_networks
DROP
CONSTRAINT FK_social_network_social_network_image;

ALTER TABLE social_networks
DROP
CONSTRAINT FK_user_social_network;

ALTER TABLE web_pages_places
DROP
CONSTRAINT FKrm26v5rrc5t54lhcd04dcwkw8;

ALTER TABLE habit_status
DROP
CONSTRAINT fk_habit_status_habit_assign_id;

ALTER TABLE message_like
DROP
CONSTRAINT fk_participant_id;

ALTER TABLE reasons_for_user_deactivation
DROP
CONSTRAINT fk_reasons_for_user_deactivation_users_id;

ALTER TABLE unread_messages
DROP
CONSTRAINT fkh84h4eq2rt6ams9mbbb0keadp;

ALTER TABLE user_actions
DROP
CONSTRAINT user_actions_users_id_fk;

ALTER TABLE users
DROP
CONSTRAINT user_language_id;

CREATE TABLE habit_comment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text              VARCHAR(8000)                           NOT NULL,
    created_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    parent_comment_id BIGINT,
    user_id           BIGINT,
    habit_id          BIGINT,
    deleted           BOOLEAN,
    CONSTRAINT pk_habit_comment PRIMARY KEY (id)
);

CREATE TABLE habit_comment_users_liked
(
    habit_comment_id BIGINT NOT NULL,
    users_liked_id   BIGINT NOT NULL,
    CONSTRAINT pk_habit_comment_users_liked PRIMARY KEY (habit_comment_id, users_liked_id)
);

ALTER TABLE eco_news_users_dislikes
    ADD CONSTRAINT pk_eco_news_users_dislikes PRIMARY KEY (eco_news_id, users_id);

ALTER TABLE eco_news_users_likes
    ADD CONSTRAINT pk_eco_news_users_likes PRIMARY KEY (eco_news_id, users_id);

ALTER TABLE econews_comment_users_liked
    ADD CONSTRAINT pk_econews_comment_users_liked PRIMARY KEY (econews_comment_id, users_liked_id);

ALTER TABLE habit_fact_translations
    ADD CONSTRAINT uc_habit_fact_translations_content UNIQUE (content);

ALTER TABLE notification
    ADD CONSTRAINT uc_notification_payload UNIQUE (payload_id);

ALTER TABLE shopping_list_item_translations
    ADD CONSTRAINT uc_shopping_list_item_translations_content UNIQUE (content);

ALTER TABLE tag_translations
    ADD CONSTRAINT uc_tag_translations_language UNIQUE (language_id);

ALTER TABLE habit_comment
    ADD CONSTRAINT FK_HABIT_COMMENT_ON_HABIT FOREIGN KEY (habit_id) REFERENCES habits (id);

ALTER TABLE habit_comment
    ADD CONSTRAINT FK_HABIT_COMMENT_ON_PARENTCOMMENT FOREIGN KEY (parent_comment_id) REFERENCES habit_comment (id);

ALTER TABLE habit_comment
    ADD CONSTRAINT FK_HABIT_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE habit_comment_users_liked
    ADD CONSTRAINT fk_habcomuselik_on_habit_comment FOREIGN KEY (habit_comment_id) REFERENCES habit_comment (id);

ALTER TABLE habit_comment_users_liked
    ADD CONSTRAINT fk_habcomuselik_on_user FOREIGN KEY (users_liked_id) REFERENCES users (id);

DROP TABLE habit_status CASCADE;

DROP TABLE message_like CASCADE;

DROP TABLE reasons_for_user_deactivation CASCADE;

DROP TABLE social_network_images CASCADE;

DROP TABLE social_networks CASCADE;

DROP TABLE unread_messages CASCADE;

DROP TABLE user_actions CASCADE;

DROP TABLE web_pages_places CASCADE;

ALTER TABLE eco_news_tags
DROP
CONSTRAINT eco_news_tags_pkey;

ALTER TABLE habit_shopping_list_items
DROP
COLUMN id;

ALTER TABLE habit_shopping_list_items
DROP
COLUMN status;

ALTER TABLE comments
DROP
COLUMN estimate_id;

ALTER TABLE comments
DROP
COLUMN place_id;

ALTER TABLE users
DROP
COLUMN language_id;

ALTER TABLE users
DROP
COLUMN phone_number;

ALTER TABLE users
DROP
COLUMN uuid;

DROP SEQUENCE address_id_seq CASCADE;

DROP SEQUENCE bag_id_seq CASCADE;

DROP SEQUENCE orders_id_seq CASCADE;

DROP SEQUENCE ubs_user_id_seq CASCADE;

ALTER TABLE habit_statistics
    ALTER COLUMN amount_of_items DROP NOT NULL;

ALTER TABLE habit_fact_translations
ALTER
COLUMN content TYPE VARCHAR(4000) USING (content::VARCHAR(4000));

ALTER TABLE habit_fact_translations
    ALTER COLUMN content SET NOT NULL;

ALTER TABLE shopping_list_item_translations
ALTER
COLUMN content TYPE VARCHAR(4000) USING (content::VARCHAR(4000));

ALTER TABLE rating_statistics
    ALTER COLUMN current_rating DROP NOT NULL;

ALTER TABLE habit_translation
ALTER
COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE econews_comment
    ALTER COLUMN eco_news_id DROP NOT NULL;

ALTER TABLE habit_status_calendar
    ALTER COLUMN enroll_date DROP NOT NULL;

ALTER TABLE rating_statistics
ALTER
COLUMN event TYPE VARCHAR(255) USING (event::VARCHAR(255));

ALTER TABLE rating_statistics
    ALTER COLUMN event DROP NOT NULL;

ALTER TABLE verify_emails
    ALTER COLUMN expiry_date DROP NOT NULL;

ALTER TABLE habit_fact_translations
    ALTER COLUMN fact_of_day_status DROP NOT NULL;

ALTER TABLE habit_statistics
    ALTER COLUMN habit_assign_id DROP NOT NULL;

ALTER TABLE habit_status_calendar
    ALTER COLUMN habit_assign_id DROP NOT NULL;

ALTER TABLE user_shopping_list
    ALTER COLUMN habit_assign_id DROP NOT NULL;

ALTER TABLE habit_fact_translations
    ALTER COLUMN habit_fact_id DROP NOT NULL;

ALTER TABLE custom_shopping_list_items
    ALTER COLUMN habit_id DROP NOT NULL;

ALTER TABLE habit_facts
    ALTER COLUMN habit_id DROP NOT NULL;

ALTER TABLE habit_translation
    ALTER COLUMN habit_id DROP NOT NULL;

ALTER TABLE habit_translation
    ALTER COLUMN habit_item SET NOT NULL;

ALTER TABLE habits
    ALTER COLUMN is_custom_habit SET NOT NULL;

ALTER TABLE habit_fact_translations
    ALTER COLUMN language_id DROP NOT NULL;

ALTER TABLE habit_translation
    ALTER COLUMN language_id DROP NOT NULL;

ALTER TABLE shopping_list_item_translations
    ALTER COLUMN language_id DROP NOT NULL;

ALTER TABLE filters
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE habit_translation
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE tag_translations
ALTER
COLUMN name TYPE VARCHAR(20) USING (name::VARCHAR(20));

ALTER TABLE rating_statistics
    ALTER COLUMN points_changed DROP NOT NULL;

ALTER TABLE users
ALTER
COLUMN profile_picture TYPE VARCHAR(255) USING (profile_picture::VARCHAR(255));

ALTER TABLE habit_assign
    ALTER COLUMN progress_notification_has_displayed SET NOT NULL;

ALTER TABLE habit_statistics
ALTER
COLUMN rate TYPE VARCHAR(255) USING (rate::VARCHAR(255));

ALTER TABLE habit_statistics
    ALTER COLUMN rate DROP NOT NULL;

ALTER TABLE users
ALTER
COLUMN role TYPE VARCHAR(255) USING (role::VARCHAR(255));

ALTER TABLE shopping_list_item_translations
    ALTER COLUMN shopping_list_item_id DROP NOT NULL;

ALTER TABLE eco_news
ALTER
COLUMN short_info TYPE VARCHAR(255) USING (short_info::VARCHAR(255));

ALTER TABLE custom_shopping_list_items
ALTER
COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

ALTER TABLE habit_assign
ALTER
COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

ALTER TABLE user_shopping_list
ALTER
COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

ALTER TABLE eco_news
ALTER
COLUMN text TYPE VARCHAR(255) USING (text::VARCHAR(255));

ALTER TABLE eco_news
ALTER
COLUMN title TYPE VARCHAR(255) USING (title::VARCHAR(255));

ALTER TABLE verify_emails
    ALTER COLUMN token DROP NOT NULL;

ALTER TABLE filters
ALTER
COLUMN type TYPE VARCHAR(255) USING (type::VARCHAR(255));

ALTER TABLE tags
ALTER
COLUMN type TYPE VARCHAR(255) USING (type::VARCHAR(255));

ALTER TABLE custom_shopping_list_items
    ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE econews_comment
    ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE filters
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE rating_statistics
    ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE habit_shopping_list_items
    ADD CONSTRAINT pk_habit_shopping_list_items PRIMARY KEY (habit_id, shopping_list_item_id);